# Schema for the configuration files of the User registration password module.

user_registrationpassword.settings:
  type: config_object
  label: 'User registration password settings'
  mapping:
    registration:
      type: string
      label: 'User registration password type'
    user_mail_status_activated_subject_original:
      type: string
      label: 'Original activated mail subject'
    user_mail_status_activated_body_original:
      type: string
      label: 'Original activated mail body'
